;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	tau/esc-quit
	tau/quit
	))

(setq mc/cmds-to-run-once
      '(
	help-for-help
	tabbar-backward-tab
	tabbar-close-tab
	tabbar-forward-tab
	))
